// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deployments.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDeployment = `-- name: CreateDeployment :one
INSERT INTO deployments (id, project_id, status, created_at, updated_at)
VALUES (gen_random_uuid(), $1, 'pending', NOW(), NOW())
RETURNING id, project_id, status, commit_sha, commit_message, image_tag, container_id, domain, created_at, updated_at
`

func (q *Queries) CreateDeployment(ctx context.Context, projectID pgtype.UUID) (Deployment, error) {
	row := q.db.QueryRow(ctx, createDeployment, projectID)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Status,
		&i.CommitSha,
		&i.CommitMessage,
		&i.ImageTag,
		&i.ContainerID,
		&i.Domain,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDeploymentLog = `-- name: CreateDeploymentLog :one
INSERT INTO deployment_logs (id, deployment_id, stream, message, created_at)
VALUES (gen_random_uuid(), $1, $2, $3, NOW())
RETURNING id, deployment_id, stream, message, created_at
`

type CreateDeploymentLogParams struct {
	DeploymentID pgtype.UUID
	Stream       string
	Message      string
}

func (q *Queries) CreateDeploymentLog(ctx context.Context, arg CreateDeploymentLogParams) (DeploymentLog, error) {
	row := q.db.QueryRow(ctx, createDeploymentLog, arg.DeploymentID, arg.Stream, arg.Message)
	var i DeploymentLog
	err := row.Scan(
		&i.ID,
		&i.DeploymentID,
		&i.Stream,
		&i.Message,
		&i.CreatedAt,
	)
	return i, err
}

const getDeploymentByID = `-- name: GetDeploymentByID :one
SELECT d.id, d.project_id, d.status, d.commit_sha, d.commit_message, d.image_tag, d.container_id, d.domain, d.created_at, d.updated_at FROM deployments d
JOIN projects p ON p.id = d.project_id
WHERE d.id = $1 AND p.user_id = $2
LIMIT 1
`

type GetDeploymentByIDParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) GetDeploymentByID(ctx context.Context, arg GetDeploymentByIDParams) (Deployment, error) {
	row := q.db.QueryRow(ctx, getDeploymentByID, arg.ID, arg.UserID)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Status,
		&i.CommitSha,
		&i.CommitMessage,
		&i.ImageTag,
		&i.ContainerID,
		&i.Domain,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestDeploymentByProject = `-- name: GetLatestDeploymentByProject :one
SELECT d.id, d.project_id, d.status, d.commit_sha, d.commit_message, d.image_tag, d.container_id, d.domain, d.created_at, d.updated_at FROM deployments d
JOIN projects p ON p.id = d.project_id
WHERE d.project_id = $1 AND p.user_id = $2
ORDER BY d.created_at DESC
LIMIT 1
`

type GetLatestDeploymentByProjectParams struct {
	ProjectID pgtype.UUID
	UserID    pgtype.UUID
}

func (q *Queries) GetLatestDeploymentByProject(ctx context.Context, arg GetLatestDeploymentByProjectParams) (Deployment, error) {
	row := q.db.QueryRow(ctx, getLatestDeploymentByProject, arg.ProjectID, arg.UserID)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Status,
		&i.CommitSha,
		&i.CommitMessage,
		&i.ImageTag,
		&i.ContainerID,
		&i.Domain,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDeploymentLogs = `-- name: ListDeploymentLogs :many
SELECT id, deployment_id, stream, message, created_at FROM deployment_logs
WHERE deployment_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListDeploymentLogs(ctx context.Context, deploymentID pgtype.UUID) ([]DeploymentLog, error) {
	rows, err := q.db.Query(ctx, listDeploymentLogs, deploymentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeploymentLog
	for rows.Next() {
		var i DeploymentLog
		if err := rows.Scan(
			&i.ID,
			&i.DeploymentID,
			&i.Stream,
			&i.Message,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeploymentsByProject = `-- name: ListDeploymentsByProject :many
SELECT d.id, d.project_id, d.status, d.commit_sha, d.commit_message, d.image_tag, d.container_id, d.domain, d.created_at, d.updated_at FROM deployments d
JOIN projects p ON p.id = d.project_id
WHERE d.project_id = $1 AND p.user_id = $2
ORDER BY d.created_at DESC
`

type ListDeploymentsByProjectParams struct {
	ProjectID pgtype.UUID
	UserID    pgtype.UUID
}

func (q *Queries) ListDeploymentsByProject(ctx context.Context, arg ListDeploymentsByProjectParams) ([]Deployment, error) {
	rows, err := q.db.Query(ctx, listDeploymentsByProject, arg.ProjectID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Deployment
	for rows.Next() {
		var i Deployment
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Status,
			&i.CommitSha,
			&i.CommitMessage,
			&i.ImageTag,
			&i.ContainerID,
			&i.Domain,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDeploymentDetails = `-- name: UpdateDeploymentDetails :one
UPDATE deployments
SET status = $2, commit_sha = $3, commit_message = $4, image_tag = $5, container_id = $6, domain = $7, updated_at = NOW()
WHERE id = $1
RETURNING id, project_id, status, commit_sha, commit_message, image_tag, container_id, domain, created_at, updated_at
`

type UpdateDeploymentDetailsParams struct {
	ID            pgtype.UUID
	Status        string
	CommitSha     string
	CommitMessage string
	ImageTag      string
	ContainerID   string
	Domain        string
}

func (q *Queries) UpdateDeploymentDetails(ctx context.Context, arg UpdateDeploymentDetailsParams) (Deployment, error) {
	row := q.db.QueryRow(ctx, updateDeploymentDetails,
		arg.ID,
		arg.Status,
		arg.CommitSha,
		arg.CommitMessage,
		arg.ImageTag,
		arg.ContainerID,
		arg.Domain,
	)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Status,
		&i.CommitSha,
		&i.CommitMessage,
		&i.ImageTag,
		&i.ContainerID,
		&i.Domain,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDeploymentStatus = `-- name: UpdateDeploymentStatus :one
UPDATE deployments
SET status = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, project_id, status, commit_sha, commit_message, image_tag, container_id, domain, created_at, updated_at
`

type UpdateDeploymentStatusParams struct {
	ID     pgtype.UUID
	Status string
}

func (q *Queries) UpdateDeploymentStatus(ctx context.Context, arg UpdateDeploymentStatusParams) (Deployment, error) {
	row := q.db.QueryRow(ctx, updateDeploymentStatus, arg.ID, arg.Status)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Status,
		&i.CommitSha,
		&i.CommitMessage,
		&i.ImageTag,
		&i.ContainerID,
		&i.Domain,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
