// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: domains.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDomain = `-- name: CreateDomain :one
INSERT INTO domains (id, project_id, domain, created_at, updated_at)
VALUES (gen_random_uuid(), $1, $2, NOW(), NOW())
RETURNING id, project_id, domain, verified, created_at, updated_at
`

type CreateDomainParams struct {
	ProjectID pgtype.UUID
	Domain    string
}

func (q *Queries) CreateDomain(ctx context.Context, arg CreateDomainParams) (Domain, error) {
	row := q.db.QueryRow(ctx, createDomain, arg.ProjectID, arg.Domain)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Domain,
		&i.Verified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDomain = `-- name: DeleteDomain :one
DELETE FROM domains WHERE id = $1 RETURNING id
`

func (q *Queries) DeleteDomain(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, deleteDomain, id)
	var id_2 pgtype.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const listDomainsByProject = `-- name: ListDomainsByProject :many
SELECT d.id, d.project_id, d.domain, d.verified, d.created_at, d.updated_at FROM domains d
JOIN projects p ON p.id = d.project_id
WHERE d.project_id = $1 AND p.user_id = $2
ORDER BY d.created_at DESC
`

type ListDomainsByProjectParams struct {
	ProjectID pgtype.UUID
	UserID    pgtype.UUID
}

func (q *Queries) ListDomainsByProject(ctx context.Context, arg ListDomainsByProjectParams) ([]Domain, error) {
	rows, err := q.db.Query(ctx, listDomainsByProject, arg.ProjectID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Domain
	for rows.Next() {
		var i Domain
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Domain,
			&i.Verified,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
