// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: envvars.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEnvVar = `-- name: CreateEnvVar :one
INSERT INTO env_vars (id, project_id, key, value, created_at, updated_at)
VALUES (gen_random_uuid(), $1, $2, $3, NOW(), NOW())
RETURNING id, project_id, key, value, created_at, updated_at
`

type CreateEnvVarParams struct {
	ProjectID pgtype.UUID
	Key       string
	Value     string
}

func (q *Queries) CreateEnvVar(ctx context.Context, arg CreateEnvVarParams) (EnvVar, error) {
	row := q.db.QueryRow(ctx, createEnvVar, arg.ProjectID, arg.Key, arg.Value)
	var i EnvVar
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Key,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEnvVar = `-- name: DeleteEnvVar :one
DELETE FROM env_vars WHERE id = $1 RETURNING id
`

func (q *Queries) DeleteEnvVar(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, deleteEnvVar, id)
	var id_2 pgtype.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const listEnvVarsByProject = `-- name: ListEnvVarsByProject :many
SELECT e.id, e.project_id, e.key, e.value, e.created_at, e.updated_at FROM env_vars e
JOIN projects p ON p.id = e.project_id
WHERE e.project_id = $1 AND p.user_id = $2
ORDER BY e.key ASC
`

type ListEnvVarsByProjectParams struct {
	ProjectID pgtype.UUID
	UserID    pgtype.UUID
}

func (q *Queries) ListEnvVarsByProject(ctx context.Context, arg ListEnvVarsByProjectParams) ([]EnvVar, error) {
	rows, err := q.db.Query(ctx, listEnvVarsByProject, arg.ProjectID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EnvVar
	for rows.Next() {
		var i EnvVar
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Key,
			&i.Value,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEnvVar = `-- name: UpdateEnvVar :one
UPDATE env_vars
SET key = $2, value = $3, updated_at = NOW()
WHERE id = $1
RETURNING id, project_id, key, value, created_at, updated_at
`

type UpdateEnvVarParams struct {
	ID    pgtype.UUID
	Key   string
	Value string
}

func (q *Queries) UpdateEnvVar(ctx context.Context, arg UpdateEnvVarParams) (EnvVar, error) {
	row := q.db.QueryRow(ctx, updateEnvVar, arg.ID, arg.Key, arg.Value)
	var i EnvVar
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Key,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
