// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: gitrepos.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGitRepository = `-- name: CreateGitRepository :one
INSERT INTO git_repositories (id, project_id, url, branch, created_at, updated_at)
VALUES (gen_random_uuid(), $1, $2, $3, NOW(), NOW())
RETURNING id, project_id, url, branch, created_at, updated_at
`

type CreateGitRepositoryParams struct {
	ProjectID pgtype.UUID
	Url       string
	Branch    string
}

func (q *Queries) CreateGitRepository(ctx context.Context, arg CreateGitRepositoryParams) (GitRepository, error) {
	row := q.db.QueryRow(ctx, createGitRepository, arg.ProjectID, arg.Url, arg.Branch)
	var i GitRepository
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Url,
		&i.Branch,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteGitRepository = `-- name: DeleteGitRepository :one
DELETE FROM git_repositories WHERE id = $1 RETURNING id
`

func (q *Queries) DeleteGitRepository(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, deleteGitRepository, id)
	var id_2 pgtype.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const getGitRepositoryByProject = `-- name: GetGitRepositoryByProject :one
SELECT g.id, g.project_id, g.url, g.branch, g.created_at, g.updated_at FROM git_repositories g
JOIN projects p ON p.id = g.project_id
WHERE g.project_id = $1 AND p.user_id = $2
LIMIT 1
`

type GetGitRepositoryByProjectParams struct {
	ProjectID pgtype.UUID
	UserID    pgtype.UUID
}

func (q *Queries) GetGitRepositoryByProject(ctx context.Context, arg GetGitRepositoryByProjectParams) (GitRepository, error) {
	row := q.db.QueryRow(ctx, getGitRepositoryByProject, arg.ProjectID, arg.UserID)
	var i GitRepository
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Url,
		&i.Branch,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
