// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Deployment struct {
	ID            pgtype.UUID
	ProjectID     pgtype.UUID
	Status        string
	CommitSha     string
	CommitMessage string
	ImageTag      string
	ContainerID   string
	Domain        string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type DeploymentLog struct {
	ID           pgtype.UUID
	DeploymentID pgtype.UUID
	Stream       string
	Message      string
	CreatedAt    pgtype.Timestamptz
}

type Domain struct {
	ID        pgtype.UUID
	ProjectID pgtype.UUID
	Domain    string
	Verified  bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type EnvVar struct {
	ID        pgtype.UUID
	ProjectID pgtype.UUID
	Key       string
	Value     string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type GitRepository struct {
	ID        pgtype.UUID
	ProjectID pgtype.UUID
	Url       string
	Branch    string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Project struct {
	ID          pgtype.UUID
	Name        string
	Description string
	UserID      pgtype.UUID
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type User struct {
	ID           pgtype.UUID
	Name         string
	Email        string
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}
