CREATE TABLE IF NOT EXISTS agent_sessions (
    id TEXT PRIMARY KEY,
    project_id INTEGER NOT NULL DEFAULT 0,
    dir_id TEXT NOT NULL DEFAULT '',
    name TEXT NOT NULL DEFAULT 'New Chat',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE agent_tasks ADD COLUMN session_id TEXT REFERENCES agent_sessions(id) ON DELETE SET NULL;
